AllCops:
  TargetRubyVersion: 2.3

Metrics:
  Enabled: false

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/FormatStringToken:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
