language: ruby
after_script:
  - cane
  - yard stats --list-undoc
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-19mode
notifications:
  email:
    on_success: always
    on_failure: always
